export const MATCH_REPOSITORY_TOKEN = 'MATCH_REPOSITORY_TOKEN';
export const FIXTURE_PROVIDER_TOKEN = 'FIXTURE_PROVIDER_TOKEN';
export const LIVE_PROVIDER_TOKEN = 'LIVE_PROVIDER_TOKEN';
export const IN_MEMORY_MATCH_REPOSITORY_TOKEN =
  'IN_MEMORY_MATCH_REPOSITORY_TOKEN';
